"""Create research records table

Revision ID: d1f07fba9b6b
Revises: 
Create Date: 2026-07-10 10:25:04.635402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1f07fba9b6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('record_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('license', sa.String(length=100), nullable=True),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_records_doi'), ['doi'], unique=True)
        batch_op.create_index(batch_op.f('ix_research_records_record_type'), ['record_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_records_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_records_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_records_title'))
        batch_op.drop_index(batch_op.f('ix_research_records_status'))
        batch_op.drop_index(batch_op.f('ix_research_records_record_type'))
        batch_op.drop_index(batch_op.f('ix_research_records_doi'))

    op.drop_table('research_records')
    # ### end Alembic commands ###
